name: alternate animations

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
    inputs:
      animation:
        description: 'Escolha a animação a ser inserida: snake ou pacman'
        required: false
        default: ''

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Update README
      run: |
        README_FILE="README.md"
        snake_code=$(cat << 'EOF'
        <div id="snake" align="center">
          <img src="https://raw.githubusercontent.com/miguel-lamazares/miguel-lamazares/output/snake.svg" alt="Snake animation" />
        </div>
        EOF
        )
        pacman_code=$(cat << 'EOF'
        <div id="pacman">
          <picture>
            <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/miguel-lamazares/miguel-lamazares/output/pacman-contribution-graph-dark.svg">
            <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/miguel-lamazares/miguel-lamazares/output/pacman-contribution-graph.svg">
            <img alt="pacman contribution graph" src="https://raw.githubusercontent.com/miguel-lamazares/miguel-lamazares/output/pacman-contribution-graph.svg">
          </picture>
        </div>
        EOF
        )
        if [[ "${{ github.event.inputs.animation }}" == "snake" ]]; then
          code_to_insert="$snake_code"
        elif [[ "${{ github.event.inputs.animation }}" == "pacman" ]]; then
          code_to_insert="$pacman_code"
        else
          current_time=$(date +%H)
          if [ $(($current_time % 2)) -eq 0 ]; then
            code_to_insert="$snake_code"
          else
            code_to_insert="$pacman_code"
          fi
        fi
        awk -v replacement="$code_to_insert" '
          BEGIN { inside = 0 }
          /<!--animacoes-->/ { inside = 1; print $0; print replacement; next }
          /<!--fim-animacoes-->/ { inside = 0 }
          !inside { print $0 }
        ' "$README_FILE" > tmpfile && mv tmpfile "$README_FILE"

    - name: Commit changes
      run: |
        if ! git diff --exit-code; then
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add "$README_FILE"
          git commit -m "🤖 update animation"
          git push
        else
          echo "No changes to commit."