name: Alterna animação no README

on:
  schedule:
    - cron: '0 */2 * * *'  # Executa a cada 2 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositório
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Rodar script Python
      run: python scripts/alterna_animacao.py

    - name: Commit e push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Atualiza animação no README" || echo "Sem mudanças"
        git push
