name: alternate animations

on:
  schedule:
    - cron: '0 */2 * * *'  # Executa a cada 2 horas
  workflow_dispatch:  # Permite execução manual

jobs:
  swap_sections:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Alternar códigos no README.md
      run: |
        # Define o arquivo README
        README_FILE="README.md"

        # Extrai o conteúdo do bloco <!--animacoes-->
        current_animation=$(awk '
          BEGIN { inside = 0 }
          /<!--animacoes-->/ { inside = 1; next }
          /<!--fim-animacoes-->/ { inside = 0; next }
          inside { print }
        ' "$README_FILE")

        # Extrai o conteúdo do bloco <!--codigo-comentado-->
        current_commented=$(awk '
          BEGIN { inside = 0 }
          /<!--codigo-comentado-->/ { inside = 1; next }
          /<!--fim-codigo-comentado-->/ { inside = 0; next }
          inside { print }
        ' "$README_FILE")

        # Substitui os blocos
        awk -v anim="$current_commented" -v commented="$current_animation" '
          BEGIN { inside_anim = 0; inside_commented = 0 }
          /<!--animacoes-->/ { inside_anim = 1; print; print anim; next }
          /<!--fim-animacoes-->/ { inside_anim = 0 }
          /<!--codigo-comentado-->/ { inside_commented = 1; print; print commented; next }
          /<!--fim-codigo-comentado-->/ { inside_commented = 0 }
          !inside_anim && !inside_commented { print }
        ' "$README_FILE" > tmpfile && mv tmpfile "$README_FILE"

    - name: Commitar mudanças
      run: |
        # Verifica se há mudanças no arquivo
        if ! git diff --exit-code; then
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add "$README_FILE"
          git commit -m "🤖 Alterna códigos entre animações"
          git push
        else
          echo "Nenhuma alteração detectada."