name: alternate animations

on:
  schedule:
    - cron: '0 */2 * * *'  # A cada 2 horas
  workflow_dispatch:  # Para rodar manualmente, se necess치rio

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Check out o reposit칩rio
      uses: actions/checkout@v2

    - name: Atualizar conte칰do no README
      run: |
        # Define o arquivo README
        README_FILE="README.md"

        # Bloco de c칩digo para "Snake"
        snake_code=$(cat << 'EOF'
        <div id="snake" align="center">
          <img src="https://raw.githubusercontent.com/miguel-lamazares/miguel-lamazares/output/snake.svg" alt="Snake animation" />
        </div>
        EOF
        )

        # Bloco de c칩digo para "Pacman"
        pacman_code=$(cat << 'EOF'
        <div id="pacman">
          <picture>
            <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/miguel-lamazares/miguel-lamazares/output/pacman-contribution-graph-dark.svg">
            <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/miguel-lamazares/miguel-lamazares/output/pacman-contribution-graph.svg">
            <img alt="pacman contribution graph" src="https://raw.githubusercontent.com/miguel-lamazares/miguel-lamazares/output/pacman-contribution-graph.svg">
          </picture>
        </div>
        EOF
        )

        # Alterna entre os blocos baseado no hor치rio
        current_time=$(date +%H)
        if [ $(($current_time % 2)) -eq 0 ]; then
          code_to_insert="$snake_code"
        else
          code_to_insert="$pacman_code"
        fi

        # Substitui o conte칰do entre os marcadores no README.md
        awk -v replacement="$code_to_insert" '
          BEGIN { inside = 0 }
          /<!--animacoes-->/ { inside = 1; print $0; print replacement; next }
          /<!--fim-animacoes-->/ { inside = 0 }
          !inside { print $0 }
        ' "$README_FILE" > tmpfile && mv tmpfile "$README_FILE"

    - name: Commit and push changes if any
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        if [ -n "$(git status --porcelain)" ]; then
          git add "$README_FILE"
          git commit -m "游뱄 update animation"
          git push
        else
          echo "No changes to commit."