name: Alternar Animação

on:
  schedule:
    - cron: "0 */6 * * *"  # A cada 6 horas
  workflow_dispatch:

jobs:
  swap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Rodar script
        run: |
          npm install
          node swap.js

      - name: Commit e Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Troca automática de animação"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}