name: Update Animation in README

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  update-animation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Debug file paths
        run: |
          echo "Current directory:"
          pwd
          echo "Files in directory:"
          ls -la

      - name: Debug update-animation.py
        run: |
          if [ -f "update-animation.py" ]; then
            echo "update-animation.py content:"
            cat update-animation.py
          else
            echo "update-animation.py not found."
            exit 1
          fi

      - name: Install dependencies (if requirements.txt exists)
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping dependencies installation."

      - name: Check and run update animation script
        run: |
          if [ -f "update-animation.py" ]; then
            python update-animation.py
          else
            echo "update-animation.py not found, skipping script execution."
            exit 1
          fi

      - name: Commit and push changes
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update animation in README" || echo "No changes to commit"
          git push