name: Update Animation in README

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"  # Executa a cada 2 horas

jobs:
  update-animation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies (if requirements.txt exists)
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi

      - name: Run update animation script
        run: |
          if [ -f "update-animation.py" ]; then
            python update-animation.py
          else
            echo "update-animation.py not found, skipping script execution."
            exit 1
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --quiet && echo "No changes to commit." || git commit -m "Update animation in README"
          git push
