name: Random GIF Updater

on:
  schedule:
    - cron: '0 */2 * * *' # Executa a cada 2 horas
  workflow_dispatch: # Permite executar manualmente

jobs:
  update-gif:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Selecionar e copiar GIF aleatório
      run: |
        python3 <<EOF
        import os
        import random
        import shutil

        gif_dir = 'gif'
        gif_list = [f for f in os.listdir(gif_dir) if f.endswith('.gif') and f != 'principal.gif']
        if not gif_list:
            raise Exception("Nenhum gif encontrado para usar.")
        selected = random.choice(gif_list)
        shutil.copy(os.path.join(gif_dir, selected), os.path.join(gif_dir, 'principal.gif'))
        print(f"Selecionado: {selected}")
        EOF

    - name: Commit e Push se houver mudanças
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add gif/principal.gif
        git diff --cached --quiet || git commit -m "🤖 randow gif updated"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
