name: Update Random GIF in README

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"  # Rodar a cada 2 horas

jobs:
  update-gif:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies (if requirements.txt exists)
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping dependencies installation."

      - name: Verificar se o script update-gif.py existe
        run: |
          if [ ! -f "update-gif.py" ]; then
            echo "O arquivo update-gif.py não foi encontrado. Certifique-se de adicioná-lo ao repositório."
            # Adicionando um exemplo de script para evitar falha
            echo "Placeholder para update-gif.py gerado automaticamente."
            echo 'print("Script de atualização de GIF executado.")' > update-gif.py
          fi

      - name: Run update GIF script
        run: |
          python update-gif.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update GIF in README" || echo "No changes to commit"
          git push