name: Update Animation in README

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"  # Rodar a cada 2 horas

jobs:
  update-animation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update animation script
        run: |
          python .github/workflows/update-animation/update_animation.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update animation in README" || echo "No changes to commit"
          git push